# GENERATED by `stel codegen` — do not edit; regenerate to update.
# stel project 'dbt_ref_roundtrip', model 'flagged_invoices'.
import os


def model(dbt, session):
    dbt.config(materialized="table")

    from stel.dbt_embed import materialize

    project_dir = os.environ["STEL_PROJECT_DIR"]
    upstreams = {
        'invoice_facts': dbt.ref('invoice_facts').pl(),
    }
    frame = materialize(
        'flagged_invoices',
        project_dir=project_dir,
        upstreams=upstreams,
        session=session,
    )
    return frame.to_arrow()
