# GENERATED by `dbt-ml codegen` — do not edit; regenerate to update.
# dbt-ml project 'dbt_ref_roundtrip', model 'raw_vendors'.
import os


def model(dbt, session):
    dbt.config(materialized="table")

    from dbt_ml.dbt_embed import materialize

    project_dir = os.environ["DBT_ML_PROJECT_DIR"]
    frame = materialize(
        'raw_vendors',
        project_dir=project_dir,
        session=session,
    )
    return frame.to_arrow()
