# GENERATED by `stel codegen` — do not edit; regenerate to update.
# stel project 'invoice_pipeline', model 'raw_invoices'.
import os


def model(dbt, session):
    dbt.config(materialized="table")

    from stel.dbt_embed import materialize

    project_dir = os.environ["STEL_PROJECT_DIR"]
    frame = materialize(
        'raw_invoices',
        project_dir=project_dir,
        session=session,
    )
    return frame.to_arrow()
