# GENERATED by `dbt-ml codegen` — do not edit; regenerate to update.
# dbt-ml project 'invoice_pipeline', model 'invoice_summary'.
import os


def model(dbt, session):
    dbt.config(materialized="table")

    from dbt_ml.dbt_embed import materialize

    project_dir = os.environ["DBT_ML_PROJECT_DIR"]
    upstreams = {
        'raw_invoices': dbt.ref('raw_invoices').pl(),
    }
    frame = materialize(
        'invoice_summary',
        project_dir=project_dir,
        upstreams=upstreams,
        session=session,
    )
    return frame.to_arrow()
