# A dbt Python model that runs the dbt-ml `raw_invoices` extraction in-process
# and hands the frame to dbt to materialize. Under the A1 authoring surface
# (#177) this thin shim is generated by `dbt-ml codegen` from the dbt-ml YAML;
# it is checked in here so the example is runnable without the codegen step.
import os
from pathlib import Path


def model(dbt, session):
    dbt.config(materialized="table")

    from dbt_ml.dbt_embed import materialize

    # The colocated dbt-ml project. An env var keeps the example location-robust;
    # codegen would bake in the project-relative path.
    project_dir = os.environ.get("DBT_ML_PROJECT_DIR")
    if project_dir is None:
        project_dir = str((Path(__file__).parents[3] / "invoice_pipeline").resolve())

    df = materialize("raw_invoices", project_dir=project_dir, session=session)
    # Arrow is the most portable hand-off to dbt-duckdb's materialization.
    return df.to_arrow()
