# GENERATED by `dbt-ml codegen` — do not edit; regenerate to update.
# dbt-ml project 'invoice_pipeline', model 'raw_invoices'.
import os


def model(dbt, session):
    dbt.config(materialized="table")

    from dbt_ml.dbt_embed import materialize

    project_dir = os.environ["DBT_ML_PROJECT_DIR"]
    frame = materialize(
        'raw_invoices',
        project_dir=project_dir,
        session=session,
    )
    return frame.to_arrow()
