"""Generate dbt Python-model shims + schema.yml from a dbt-ml project (#177, A1).

The dbt-ml YAML stays the source of truth; `dbt-ml codegen` emits, for each
embeddable model, a thin dbt Python model that calls `dbt_ml.dbt_embed.materialize`
plus one `schema.yml` carrying the models' fields and tests. The emitted `.py`
files are real dbt nodes, so dbt orders them, `ref()`s resolve across dbt and
dbt-ml, and `dbt docs` shows one lineage graph.

Prototype scope (#177): extraction and transform models on dbt-duckdb. Each
transform reads its upstream dbt-ml dependencies from `dbt.ref(...)` inside the
shim and passes them to `materialize(upstreams=...)`.
"""
from __future__ import annotations

from pathlib import Path

import yaml

from ..config import load_project
from ..config.model import ModelConfig
from ..dag import parse_ref
from ..dbt_export import _table_for_model

_GENERATED_HEADER = (
    "# GENERATED by `dbt-ml codegen` — do not edit; regenerate to update.\n"
    "# dbt-ml project {project!r}, model {model!r}.\n"
)


def generate_dbt_models(
    project_dir: str | Path,
    out_dir: str | Path,
    *,
    source_name: str | None = None,
) -> list[Path]:
    """Write one `<model>.py` shim per embeddable model plus a shared
    `schema.yml` into `out_dir`. Returns the paths written."""
    project_path = Path(project_dir)
    project, _sources, models = load_project(project_path)

    embeddable = [m for m in models if m.extraction is not None or m.transform is not None]
    skipped = [m.name for m in models if m not in embeddable]

    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    for model in embeddable:
        shim_path = out_path / f"{model.name}.py"
        shim_path.write_text(_render_shim(project.name, model), encoding="utf-8")
        written.append(shim_path)

    name = source_name or f"dbt_ml_{project.name}"
    schema = {
        "version": 2,
        "models": [_model_entry(_table_for_model(m, source_name=name)) for m in embeddable],
    }
    schema_path = out_path / "schema.yml"
    schema_path.write_text(
        _GENERATED_HEADER.format(project=project.name, model="<all>")
        + yaml.safe_dump(schema, sort_keys=False),
        encoding="utf-8",
    )
    written.append(schema_path)

    if skipped:
        # Search/chunk/embed/ml/llm models aren't in the embedded prototype yet;
        # name them so the operator knows they weren't emitted.
        (out_path / "_SKIPPED.txt").write_text(
            "Not emitted (embedded prototype supports extraction/transform only):\n"
            + "\n".join(f"  - {n}" for n in skipped)
            + "\n",
            encoding="utf-8",
        )
    return written


def _model_entry(table: dict[str, object]) -> dict[str, object]:
    """`_table_for_model` builds a v2 source-table dict; a model entry in
    schema.yml shares the same shape (name/description/columns/tests/meta), so we
    reuse it verbatim."""
    return table


def _render_shim(project_name: str, model: ModelConfig) -> str:
    deps = [parse_ref(d) for d in (model.depends_on or [])]
    name = model.name

    lines = [
        _GENERATED_HEADER.format(project=project_name, model=name).rstrip("\n"),
        "import os",
        "",
        "",
        "def model(dbt, session):",
        # dbt owns materialization; embedded mode always hands dbt a full frame.
        '    dbt.config(materialized="table")',
        "",
        "    from dbt_ml.dbt_embed import materialize",
        "",
        '    project_dir = os.environ["DBT_ML_PROJECT_DIR"]',
    ]

    if deps:
        lines.append("    upstreams = {")
        for dep in deps:
            # dbt.ref(...) is statically parsed into the DAG; .pl() yields polars.
            lines.append(f"        {dep!r}: dbt.ref({dep!r}).pl(),")
        lines.append("    }")

    # Emit the call wrapped so generated lines stay within the 100-col limit.
    lines.append("    frame = materialize(")
    lines.append(f"        {name!r},")
    lines.append("        project_dir=project_dir,")
    if deps:
        lines.append("        upstreams=upstreams,")
    lines.append("        session=session,")
    lines.append("    )")
    lines.append("    return frame.to_arrow()")
    lines.append("")
    return "\n".join(lines)
