# GENERATED by `stel codegen` — do not edit; regenerate to update.
# stel project 'invoice_pipeline', model 'monthly_totals'.
import os


def model(dbt, session):
    dbt.config(materialized="table")

    from stel.dbt_embed import materialize

    project_dir = os.environ["STEL_PROJECT_DIR"]
    upstreams = {
        'raw_invoices': dbt.ref('raw_invoices').pl(),
    }
    frame = materialize(
        'monthly_totals',
        project_dir=project_dir,
        upstreams=upstreams,
        session=session,
    )
    return frame.to_arrow()
