"""Generate dbt Python-model shims + schema.yml from a stel project (#177, A1).

The stel YAML stays the source of truth; `stel codegen` emits, for each
embeddable model, a thin dbt Python model that calls `stel.dbt_embed.materialize`
plus one `schema.yml` carrying the models' fields and tests. The emitted `.py`
files are real dbt nodes, so dbt orders them, `ref()`s resolve across dbt and
stel, and `dbt docs` shows one lineage graph.

Prototype scope (#177): extraction and transform models on dbt-duckdb. Each
transform reads its upstream stel dependencies from `dbt.ref(...)` inside the
shim and passes them to `materialize(upstreams=...)`.
"""
from __future__ import annotations

from pathlib import Path

import yaml

from ..config import load_project
from ..config.model import ModelConfig
from ..dag import is_dbt_ref, parse_dbt_ref, parse_ref
from ..dbt_export import _table_for_model

_GENERATED_HEADER = (
    "# GENERATED by `stel codegen` — do not edit; regenerate to update.\n"
    "# stel project {project!r}, model {model!r}.\n"
)


def generate_dbt_models(
    project_dir: str | Path,
    out_dir: str | Path,
    *,
    source_name: str | None = None,
) -> list[Path]:
    """Write one `<model>.py` shim per embeddable model plus a shared
    `schema.yml` into `out_dir`. Returns the paths written."""
    project_path = Path(project_dir)
    project, _sources, models = load_project(project_path)

    embeddable = _embeddable_models(models)
    embeddable_names = {m.name for m in embeddable}
    skipped = [m.name for m in models if m.name not in embeddable_names]

    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    for model in embeddable:
        shim_path = out_path / f"{model.name}.py"
        shim_path.write_text(_render_shim(project.name, model), encoding="utf-8")
        written.append(shim_path)

    name = source_name or f"dbt_ml_{project.name}"
    schema = {
        "version": 2,
        "models": [_model_entry(_table_for_model(m, source_name=name)) for m in embeddable],
    }
    schema_path = out_path / "schema.yml"
    schema_path.write_text(
        _GENERATED_HEADER.format(project=project.name, model="<all>")
        + yaml.safe_dump(schema, sort_keys=False),
        encoding="utf-8",
    )
    written.append(schema_path)

    if skipped:
        # Two reasons a model isn't emitted: its kind is unsupported by the
        # embedded prototype (chunk/embed/llm/ml/search), or it's a transform
        # that (transitively) depends on such a model — emitting it would write
        # a dbt.ref() to a node that doesn't exist and break `dbt parse`.
        (out_path / "_SKIPPED.txt").write_text(
            "Not emitted (embedded prototype supports extraction/transform models\n"
            "whose dependencies are all themselves emittable):\n"
            + "\n".join(f"  - {n}" for n in skipped)
            + "\n",
            encoding="utf-8",
        )
    return written


def _embeddable_models(models: list[ModelConfig]) -> list[ModelConfig]:
    """Models emittable as dbt nodes: extraction/transform kinds whose full
    dependency closure is also emittable. A transform depending on a non-emitted
    model (chunk/embed/llm/ml/search — or another skipped transform) is dropped
    so the generated project never references a missing dbt node."""
    by_name = {m.name: m for m in models}
    keep = {m.name for m in models if m.extraction is not None or m.transform is not None}

    # Fixed-point removal: drop any kept model with a dependency outside `keep`,
    # repeating so a skip propagates to everything downstream of it.
    changed = True
    while changed:
        changed = False
        for name in list(keep):
            deps = [parse_ref(d) for d in (by_name[name].depends_on or [])]
            if any(dep not in keep for dep in deps):
                keep.discard(name)
                changed = True

    return [m for m in models if m.name in keep]


def _model_entry(table: dict[str, object]) -> dict[str, object]:
    """`_table_for_model` builds a v2 source-table dict; a model entry in
    schema.yml shares the same shape (name/description/columns/tests/meta), so we
    reuse it verbatim."""
    return table


def _render_shim(project_name: str, model: ModelConfig) -> str:
    deps = [parse_ref(d) for d in (model.depends_on or [])]
    # A dbt_ref('...') source (#177) is fed in exactly like a stel upstream:
    # the shim reads dbt.ref('name') and passes the frame through `upstreams`,
    # and dbt orders the dbt-built table before this node.
    if model.source and is_dbt_ref(model.source):
        deps = [parse_dbt_ref(model.source), *deps]
    name = model.name

    lines = [
        _GENERATED_HEADER.format(project=project_name, model=name).rstrip("\n"),
        "import os",
        "",
        "",
        "def model(dbt, session):",
        # dbt owns materialization; embedded mode always hands dbt a full frame.
        '    dbt.config(materialized="table")',
        "",
        "    from stel.dbt_embed import materialize",
        "",
        '    project_dir = os.environ["STEL_PROJECT_DIR"]',
    ]

    if deps:
        lines.append("    upstreams = {")
        for dep in deps:
            # dbt.ref(...) is statically parsed into the DAG; .pl() yields polars.
            lines.append(f"        {dep!r}: dbt.ref({dep!r}).pl(),")
        lines.append("    }")

    # Emit the call wrapped so generated lines stay within the 100-col limit.
    lines.append("    frame = materialize(")
    lines.append(f"        {name!r},")
    lines.append("        project_dir=project_dir,")
    if deps:
        lines.append("        upstreams=upstreams,")
    lines.append("        session=session,")
    lines.append("    )")
    lines.append("    return frame.to_arrow()")
    lines.append("")
    return "\n".join(lines)
